### ISSUE TITLE
Hello，Does the demo support CAD mode? Does LLCC68 support?

### ISSUE THREAD

**Issue by niubbbbbbbb** [nopnop2002/esp-idf-sx126x#10]

**Comment by nopnop2002** [comment]
What is  CAD mode? 

LLCC68 is used for Ra-01SC.   
LLCC68 is compatible with SX126X.   
However, there are the following restrictions:   
- BW is either 125KHz, 250KHz or 500Khz.   
- When BW is 125KHz, SF is in the range of 5-9.   
- When BW is 250KHz, SF is in the range of 5-10.   
- When BW is 500KHz, SF is in the range of 5-11.

**Comment by niubbbbbbbb** [comment]
CAD is Channel Activity Detection

**Comment by nopnop2002** [comment]
This library does not support CAD.

**Comment by niubbbbbbbb** [comment]
Do you have support CAD's library?

**Comment by niubbbbbbbb** [comment]
Can CAD functions be added to this library? Is there any problem in adding CAD functions to the library

**Comment by nopnop2002** [comment]
there is no problem in adding CAD functions to the library.

**Comment by niubbbbbbbb** [comment]
thanks

**Comment by nopnop2002** [comment]
I added SetCadParams() and SetCad().

You can specify the following constants in SetCadParams().

```
//SX126X_CMD_SET_CAD_PARAMS
#define SX126X_CAD_ON_1_SYMB                          0x00        //  7     0     number of symbols used for CAD: 1
#define SX126X_CAD_ON_2_SYMB                          0x01        //  7     0                                     2
#define SX126X_CAD_ON_4_SYMB                          0x02        //  7     0                                     4
#define SX126X_CAD_ON_8_SYMB                          0x03        //  7     0                                     8
#define SX126X_CAD_ON_16_SYMB                         0x04        //  7     0                                     16
#define SX126X_CAD_GOTO_STDBY                         0x00        //  7     0     after CAD is done, always go to STDBY_RC mode
#define SX126X_CAD_GOTO_RX                            0x01        //  7     0     after CAD is done, go to Rx mode if activity is detected
```

At the end of the search period, the device triggers the IRQ CADdone if it has been enabled. 
If a valid signal has been detected it also generates the IRQ CadDetected.
These can be read using GetIrqStatus().

**Comment by niubbbbbbbb** [comment]
That means you can use the CAD function directly, right

**Comment by nopnop2002** [comment]
yes.
you are right.
If you use the CAD function, you need to read the datasheet.

**Comment by niubbbbbbbb** [comment]
Thank you so much, brother
