### ISSUE TITLE
abort() istead of while(1) { vTaskDelay(1); }?

### ISSUE THREAD

**Issue by Glowman554** [nopnop2002/esp-idf-sx126x#14]
Wouldn't it be better to use `abort()` or some other sort of error handler instead of `while(1) { vTaskDelay(1); }` when an error occurs? It would allow the user to handle errors or at least auto reboot the esp32.

**Comment by nopnop2002** [comment]
You can auto-restart with esp_restart().

However, unless the error is recovered, it will auto-restart forever.

**Comment by Glowman554** [comment]
For development purposes esp-idf allows you to turn auto restarts off. It allows you to have the feature when deploying.

**Comment by nopnop2002** [comment]
>For development purposes esp-idf allows you to turn auto restarts off. 

how do i set it?

**Comment by Glowman554** [comment]
Using CONFIG_ESP_SYSTEM_PANIC_PRINT_HALT halts the cpu instead of rebooting. I think it is located under components - > esp system settings

**Comment by Glowman554** [comment]
The default configuration is CONFIG_ESP_SYSTEM_PANIC_PRINT_REBOOT

**Comment by nopnop2002** [comment]
>Using CONFIG_ESP_SYSTEM_PANIC_PRINT_HALT halts the cpu instead of rebooting. I think it is located under components - > esp system settings

Thank you

**Comment by Glowman554** [comment]
Hey would it be ok if i implement a error callback function which by default uses `while(1) { vTaskDelay(1); }` but can be overwritten by the user using weak linking?

**Comment by nopnop2002** [comment]
>Hey would it be ok if i implement a error callback function which by default uses while(1) { vTaskDelay(1); } but can be overwritten by the user using weak linking?

Try it.
