### ISSUE TITLE
SetTx Illegal Status

### ISSUE THREAD

**Issue by testqaibs** [nopnop2002/esp-idf-sx126x#17]
Hi,

I am facing "SetTx Illegal Status" issue. I am using EBYTE E22-900M30S and I have set the frequency to 915 MHz. I have also increased the timeout to 3000Ms. 

Please have a look at my debug print:

I (7407) LoRa126x: WriteCommand: CMD=0x8c
I (7467) LoRa126x: 00 --> d2
I (7487) LoRa126x: 08 --> d2
I (7527) LoRa126x: 00 --> d2
I (7547) LoRa126x: 18 --> d2
I (7577) LoRa126x: 01 --> d2
I (7607) LoRa126x: 00 --> d2
I (7607) LoRa126x: WriteCommand: CMD=0x02
I (7667) LoRa126x: 03 --> d2
I (7687) LoRa126x: ff --> d2
I (8407) LoRa126x: ----- SetTx timeoutInMs=3000
I (8407) LoRa126x: WriteCommand: CMD=0x80
I (8467) LoRa126x: 00 --> d2
I (8467) LoRa126x: SetTxEnable:SX126x_TXEN=-1 SX126x_RXEN=-1
I (8467) LoRa126x: SetTx timeoutInMs=3000 tout=192000000
I (8467) LoRa126x: WriteCommand: CMD=0x83
I (8527) LoRa126x: 71 --> a2
I (8547) LoRa126x: b0 --> a2
I (8587) LoRa126x: 00 --> a2
I (8597) LoRa126x: ReadCommand: CMD=0xc0
I (8657) LoRa126x: DataIn:62
I (8657) LoRa126x: ReadCommand: CMD=0xc0
I (8717) LoRa126x: DataIn:2c
E (8717) LoRa126x: SetTx Illegal Status

Please guide me if I am missing anything. 

--
Thanks,
Pravin

**Comment by nopnop2002** [comment]
I don't have this one.
With this change it may work.
```
	//float tcxoVoltage = 0.0; // don't use TCXO
	//bool useRegulatorLDO = false; // use only LDO in all modes

	float tcxoVoltage = 3.3; // use TCXO
	bool useRegulatorLDO = true; // use TCXO
```

**Comment by testqaibs** [comment]
Thanks! After "use TCXO" and Pin connection as mentioned in https://github.com/nopnop2002/esp-idf-sx126x/pull/5#issue-1323583221 it starts working...

**Comment by nopnop2002** [comment]
>Pin connection as mentioned in https://github.com/nopnop2002/esp-idf-sx126x/pull/5#issue-1323583221 it starts working

I would like to know more about the wiring you did.

**Comment by testqaibs** [comment]
<html>
<body>
<table>
  <tr>
    <th>SX126X</th>
    <th>ESP32-C3</th>
 </tr>
  <tr>
    <td>BUSY</td>
    <td>GPIO18</td>
  </tr>
  <tr>
    <td>RST</td>
    <td>GPIO19</td>
  </tr>
  <tr>
    <td>TXEN</td>
    <td>-1</td>
  </tr>
  <tr>
    <td>RXEN</td>
    <td>-1</td>
  </tr>
  <tr>
    <td>MISO</td>
    <td>GPIO2</td>
  </tr>
  <tr>
    <td>SCK</td>
    <td>GPIO6</td>
  </tr>
  <tr>
    <td>MOSI</td>
    <td>GPIO7</td>
  </tr>
  <tr>
    <td>NSS</td>
    <td>GPIO10</td>
  </tr>
<tr>
    <td>GND</td>
    <td>GND</td>
  </tr>
<tr>
    <td>VCC</td>
    <td>3.3V</td>
  </tr>
</table>
</body>
</html>

**Comment by nopnop2002** [comment]
Do we need this?

DIO2 pin on Ebyte module must be connected to TXEN pin on Ebyte module

**Comment by testqaibs** [comment]
No, I have not used DIO2 pin or any other pins. I have used only those pins as shown in the above table. 
I have tested the sender/receiver code with 433 MHz and 915 MHz. It is working properly.

**Comment by nopnop2002** [comment]
Thank you.
