### ISSUE TITLE
SET SYNC word

### ISSUE THREAD

**Issue by abhi-ratnman** [nopnop2002/esp-idf-sx126x#18]
Hi, Thanks for the amazing library. 

I have earlier used sandeep mistry's library with arduino ([Link for your refrence](https://github.com/sandeepmistry/arduino-LoRa)). In that there is a function named [setsync ](https://github.com/sandeepmistry/arduino-LoRa/blob/55d49c577ac678ed46bcebdba0365ad3b3cdf643/src/LoRa.cpp#L580)word, that is used to isolate the network based on the sync word. I checked your library but there is no such function for setting the sync word. Can you check and let me know if the function is available but i am unable to figure it out. 

thanks in advance

**Comment by nopnop2002** [comment]
Unfortunately, there is a function to set SyncWord.

The syncword can be used to isolate networks of LoRa devices. 
A receiver using one syncword will not (mostly) receive packets from a transmitter using a different Syncword.
However, it is not 100% certain.

Pls read this.
https://forum.arduino.cc/t/question-about-lora-setsyncword-option/869247
https://forum.arduino.cc/t/what-is-sync-word-lora/629624/5

**Comment by abhi-ratnman** [comment]
@nopnop2002 yes i want to isolate the network that is why i want to use that. Is it possible to integrate sync word in your code? I have tested that with the above library 95% of the times the networks are isolated which servers my application. it would be great help if you can provide a basic implementation of a function to change the sync word.

**Comment by nopnop2002** [comment]
I will consider.

**Comment by nopnop2002** [comment]
Added SetSyncWord function.

**Comment by abhi-ratnman** [comment]
@nopnop2002 thanks for the quick response and fix. I will test it and let you know the results in coming week.
