### ISSUE TITLE
RA-01-SH: WIFI Conflict

### ISSUE THREAD

**Issue by pluzmedia** [nopnop2002/esp-idf-sx126x#22]
Hi,
RA-01-SH, utilizing SX1262, operates properly until the invocation of esp_wifi_start(); && esp_wifi_connect();. Below are the pin configurations, utilizing SPI2 host:
`
Clk = 18
Mosi = 23
Miso = 19
CS = 16
DIO1 = 15
RST = 22
BUSY = 13
`
Thanks

**Comment by nopnop2002** [comment]
These samples use it at the same time as WiFi.

https://github.com/nopnop2002/esp-idf-sx126x/tree/main/http
https://github.com/nopnop2002/esp-idf-sx126x/tree/main/mqtt

**Comment by pluzmedia** [comment]
Thanks, It's a great library.
