### ISSUE TITLE
Platform agnostic driver implementation

### ISSUE THREAD

**Issue by kazetsukaimiko** [nopnop2002/esp-idf-sx126x#24]
Continuing our conversation from here: https://github.com/nopnop2002/Arduino-LoRa-Ra01S/pull/16

(I know a little bit of Japanese, by the way)

I'm looking at this repo, and there are a few things I'd like to contribute, but wanted to get your input first.

1. Your solution is far better than RTOS Semaphores. 
2. I like that there is no Arduino includes...  but I also think you don't really need ESP-IDF baked into it either.  See [isotp-c](https://github.com/SimonCahill/isotp-c) as an example. You would just need an abstraction for the SPI communication layer.
3. I think the first point is better accomplished with C++, I noticed you changed `SX126x` from a class to a collection of methods.  I like the C++ approach a bit better to allow for multiple SPI / LoRa chip instances, although this is quite rare I would imagine.
4. This repo is a bit messy with the real header / source buried two layers deep (`components/ra01s`) versus the example code which could go under an `examples` directory

To conclude I was wondering if you would accept any of the following refactors:

- Abstract out SPI bus concerns entirely + Make an ESP-IDF implementation of that abstraction.
- Move back a bit to the C++ style design for easier multiple LoRa chip support
- Reorganize the example code under `examples`

**Comment by nopnop2002** [comment]
I feel that ESP-IDF's C++ is very limited, what do you think?

For example, WiFi initialization and SPI device initialization do not work correctly in C++.
