### ISSUE TITLE
lowDataRateOptimize parameter

### ISSUE THREAD

**Issue by alessandrv** [nopnop2002/esp-idf-sx126x#25]
Hello, I can't find any info on how lowDataRateOptimize works and how it helps the comunication. I'm currently using a e22 900m30s by ebyte and want to get the most range, with less noise/errors in my message, no need the comunication speed to be fast or anything just need range and accuracy. I checked datasheet by my module, it looks like it supports a spreading factor up to 12 but not sure if I should change also the bandwith afterwards to fit this or what. Also I'm interested in lowDataRateOptimize param because I will be mainly sending short strings over lora

**Comment by nopnop2002** [comment]
Sorry for the late reply.

lowDataRateOptimize is very difficult to understand.
I don't understand the exact behavior either.
It is necessary to decipher the data sheet of SX126X.
