### ISSUE TITLE
Small fix

### ISSUE THREAD

**Issue by zkoalexey** [nopnop2002/esp-idf-sx126x#3]
Find:
67	gpio_reset_pin(SX126x_BUSY);
68	gpio_set_direction(SX126x_RESET, GPIO_MODE_INPUT);

Should(I think):
67	gpio_reset_pin(SX126x_BUSY);
68	gpio_set_direction(SX126x_BUSY, GPIO_MODE_INPUT);

**Comment by nopnop2002** [comment]
Thank you for reporting.
Fixed.
