### ISSUE TITLE
I have a very urgent question.Please answer, I will thank you very much

### ISSUE THREAD

**Issue by niubbbbbbbb** [nopnop2002/esp-idf-sx126x#7]
When I read your code, I found that DIO1/DIO2/DIO3 pin was not defined in your code, and then found SetDioIrqParams (SX126X_IRQ_ALL, SX126X_IRQ_NONE, X126X_IRQ_NONE, SX126X_IRQ_NONE); This function. The parameter of this function is the pin of DIO1/DIO2/DIO3 pin_ bit_ mask？
    In addition, when I read the SX1262 data manual, I did not find RXEN and TXEN. What are the two pins in the data manual?
If you can help me answer these two questions, I will thank you very much.
![image](https://user-images.githubusercontent.com/116434014/197334893-3a87fade-0a10-4a5d-9a01-79f18876f211.png)

**Comment by nopnop2002** [comment]
```

// DIO and IRQ control
#define SX126X_CMD_SET_DIO_IRQ_PARAMS                 0x08




void SetDioIrqParams
( uint16_t irqMask, uint16_t dio1Mask, uint16_t dio2Mask, uint16_t dio3Mask )
{
    uint8_t buf[8];

    buf[0] = (uint8_t)((irqMask >> 8) & 0x00FF);
    buf[1] = (uint8_t)(irqMask & 0x00FF);
    buf[2] = (uint8_t)((dio1Mask >> 8) & 0x00FF);
    buf[3] = (uint8_t)(dio1Mask & 0x00FF);
    buf[4] = (uint8_t)((dio2Mask >> 8) & 0x00FF);
    buf[5] = (uint8_t)(dio2Mask & 0x00FF);
    buf[6] = (uint8_t)((dio3Mask >> 8) & 0x00FF);
    buf[7] = (uint8_t)(dio3Mask & 0x00FF);
    WriteCommand(SX126X_CMD_SET_DIO_IRQ_PARAMS, buf, 8); // 0x08
}
````

See "DIO and IRQ Contro" in the datasheet.


In general, use DIO2 to switch the RF-Switch.
However, some tranceiver use an external gpio to switch the RF-Switch.
RXEN and TXEN are used to toggle the RF switch.
Ra-01S / Ra-01SH use the SC70-6 integrated load switch to switch between RFO and RFI.
Ra-01S / Ra-01SH use DIO2 to control this.
