### ISSUE TITLE
E (456) RA01S: SetRx Illegal Status

### ISSUE THREAD

**Issue by niubbbbbbbb** [nopnop2002/esp-idf-sx126x#8]
Hello, how to solve this problem.

**Comment by nopnop2002** [comment]
If that doesn't work, enable [LoRaDebugPrint](https://github.com/nopnop2002/esp-idf-sx126x/blob/main/basic/main/main.c#L101).

**Comment by niubbbbbbbb** [comment]
Do you play telegram or wechat? Can you add your friends to discuss it?

**Comment by nopnop2002** [comment]
>Do you play telegram or wechat?

No

**Comment by niubbbbbbbb** [comment]
😂😂All right.My English is not good either

**Comment by niubbbbbbbb** [comment]
I think the log is not disabled. I'll show you my log. Please analyze it. I think it may be that I regret an error value after writing the command
![image](https://user-images.githubusercontent.com/116434014/197371394-2d02ad08-7a6c-419d-ab58-cabed5d8f11a.png)

**Comment by nopnop2002** [comment]
0x86 is Set the RF frequency of the radio.

You may be using the wrong frequency.

RA-01S is 410-525Mhz.
